from .tab_live import create_tab_live, wire_tab_live_events, _cleanup_active_processes, recognize_faces
from .tab_database import create_tab_database, wire_tab_database_events, refresh_database_view, update_both_person_dropdowns, get_person_dropdown_choices
from .tab_media import create_tab_media, wire_tab_media_events, handle_open_external_video
from .tab_events import create_tab_events, wire_tab_events_events
from .tab_sorter import create_tab_sorter, wire_tab_sorter_events
from .tab_settings import create_tab_settings, wire_tab_settings_events
